export const TYPES = {
  SET_CAR_POSITION_AND_VISIBLITY: "SET_CAR_POSITION_AND_VISIBLITY",
  CAR_MOVE_RIGHT: "CAR_MOVE_RIGHT",
  CAR_MOVE_LEFT: "CAR_MOVE_LEFT",
  SELECT_EXP_LEVEL: "SELECT_EXP_LEVEL",
  SET_SCREEN_NUM: "SET_SCREEN_NUM"
}